<?php

use Illuminate\Database\Seeder;

class Alm_SuministrosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100001','nomsuministro'=>'PAPEL BOND OFICIO  DE 75 GRS','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100002','nomsuministro'=>'PAPEL BOND CARTA DE 75 GRS','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100003','nomsuministro'=>'PAPEL CUBO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100004','nomsuministro'=>'PAPEL FOTOGRAFICO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100005','nomsuministro'=>'PAPEL CARBONICO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100006','nomsuministro'=>'PAPEL LUSTROSO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100007','nomsuministro'=>'PAPEL COPIA BLANCO T/ CARTA','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100008','nomsuministro'=>'PAPEL COPIA BLANCO T/ OFICIO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100009','nomsuministro'=>'PAPEL SABANA RESMA','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100010','nomsuministro'=>'PAPEL MADERA TAMAÑO RESMA','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100011','nomsuministro'=>'PAPEL CONTINUO 9 1/2X11X1','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100012','nomsuministro'=>'PAPEL CONTINUO 9 1/2X11X2','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100013','nomsuministro'=>'PAPEL CONTINUO 9 1/2X11X3','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100014','nomsuministro'=>'PAPEL CONTINUO 9 1/2X11X4','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100015','nomsuministro'=>'PAPEL CONTINUO 14 1/2X11X2','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100016','nomsuministro'=>'PAPEL CONTINUO 14 1/2X11X3','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>1,'codsuministro'=>'100017','nomsuministro'=>'PAPEL DE COLORES T/ OFICIO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200001','nomsuministro'=>'ARCHIVADOR DE PALANCA T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200002','nomsuministro'=>'ARCHIVADOR EXTRA GRANDE BRINDER','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200003','nomsuministro'=>'ARCHIVADOR DE PAL. MEDIO LOMO T/O','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200004','nomsuministro'=>'ARCHIVADOR DE PALANCA 1/2 OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200005','nomsuministro'=>'CARTULINA BLANCA T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200006','nomsuministro'=>'COMPROBANTES DE CONTAB. EGRESO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200007','nomsuministro'=>'COMPROBANTES DE CONTA TRASPASO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200008','nomsuministro'=>'CONTRATO BLOCKS Tam. Of. Original y 2 copias CON GARANTIA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200009','nomsuministro'=>'SOLICITUD BLOCKS Tam. Of. Original y 2copias CON GARANTIA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200010','nomsuministro'=>'CONTRATO REGULARES BLOCKS  Original y 2 copias SIN GARANTIA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200011','nomsuministro'=>'SOLICITUD REGULARES BLOCKS  Original y 2 copias SIN GARANTIA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200012','nomsuministro'=>'CUADERNO ESPIRAL T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200013','nomsuministro'=>'CUADERNO ESPIRAL TlCARTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200014','nomsuministro'=>'CUADERNO ESPIRAL TAMAÑO MEDIO OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200015','nomsuministro'=>'CUADERNO SIN ESPIRAL T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200016','nomsuministro'=>'LIBRO DE ACTAS  Hjas.100','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200017','nomsuministro'=>'DOCUMENTO OBLIGATORIO Cargo de Cta. Documentada','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200018','nomsuministro'=>'ESQUELA DE CONDOLENCIAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200019','nomsuministro'=>'FOLDERS AMARILLOS T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200020','nomsuministro'=>'FOLDERS AMARILLOS T/CARTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200021','nomsuministro'=>'FOLDERS INSTITUCIONALES 2016-2019','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200022','nomsuministro'=>'ARCHIVADOR COLOR NARANJA TAMAÑO OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200023','nomsuministro'=>'INFORME ECONOMICO MENSUAL','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200024','nomsuministro'=>'INGRESO ALMACEN T/CARTA BLOKS','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200025','nomsuministro'=>'LIBRETA BANCARIA M/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200026','nomsuministro'=>'LIBRETA BANCARIA M/CARTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200027','nomsuministro'=>'MEMORANDUMS','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200028','nomsuministro'=>'FACTURAS CASA COMUNITARIA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200029','nomsuministro'=>'FACTURAS UNIDAD EDUCATIVA INGAVI','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200030','nomsuministro'=>'HOJAS KARDEX 1/2 OFICIO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200031','nomsuministro'=>'ORDEN DE COMPRA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200032','nomsuministro'=>'PAPEL MEMBRETADO T/ESQUELA HILADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200033','nomsuministro'=>'PAPEL MEMBRETADO T/OFICIO','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200034','nomsuministro'=>'PAPEL MEMBRETADO T/CARTA','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200035','nomsuministro'=>'PAPEL PARA CALCULADORA ROLLOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200036','nomsuministro'=>'PAPEL PARA FAX ROLLOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200037','nomsuministro'=>'PEDIDOS DE ALMACEN T 1/2 OFICIO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200038','nomsuministro'=>'PLANILLA RENDICION DE CUENTAS','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200039','nomsuministro'=>'RECIBO DE CAJA CHICA','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200041','nomsuministro'=>'RECIBO HOSPEDAJE EN TRANSITO','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200042','nomsuministro'=>'RECIBO HOSPEDAJE PERMANENTE','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200045','nomsuministro'=>'RECIBO MAUSOLEO FILIAL CCBB','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200046','nomsuministro'=>'RECIBO HOSPEDAJE FILIAL CCBB','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200047','nomsuministro'=>'SOBRES MANILA 1/2 OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200048','nomsuministro'=>'SOBRES MANILA T/CARTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200049','nomsuministro'=>'SOBRES MANILA T/OF.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200050','nomsuministro'=>'SOBRES MANILA EXTRAGRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200051','nomsuministro'=>'SOBRES  MANILLA DOBLE OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200052','nomsuministro'=>'VALES DE TRANSPORTE T/18X11 BLOCKS','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200053','nomsuministro'=>'CAJAS DE CARTON CORRUGADO','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200054','nomsuministro'=>'TARJETAS PVC','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200055','nomsuministro'=>'CARTULINA HILADA T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200056','nomsuministro'=>'CERTIFICADOS CONDECORATIVOS 25 AÑOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200057','nomsuministro'=>'CERTIFICADOS CONDECORATIVOS 35 AÑOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200058','nomsuministro'=>'FORMULARIOS DE ACEPTACION BLOCK','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200059','nomsuministro'=>'FORMULARIOS PRES. REQUISITOS CUMPLIMIENTO BLOCK','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200060','nomsuministro'=>'FORMULARIOS PRES. REQUISITOS JUBILACION BLOCK','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200061','nomsuministro'=>'SOBRES BLANCOS T/CARTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200062','nomsuministro'=>'SOBRES BLANCOS T/OF.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200063','nomsuministro'=>'HOJAS DE TRABAJO DE 14 COLUMNAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200064','nomsuministro'=>'HOJAS DE TRABAJO DE 11 COLUMNAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200065','nomsuministro'=>'HOJAS DE TRABAJO DE 7 COLUMNAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>2,'codsuministro'=>'200066','nomsuministro'=>'FORMULARIOS DE FILIACION','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300001','nomsuministro'=>'ALFILERES CAJITA','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300002','nomsuministro'=>'BOLIGRAFO AZUL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300003','nomsuministro'=>'BOLIGRAFO NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300004','nomsuministro'=>'BOLIGRAFO ROJO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300005','nomsuministro'=>'MICROPUNTAS 0,5  AZUL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300006','nomsuministro'=>'MICROPUNTAS 0,7 PENTEL ENER GEL AZUL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300007','nomsuministro'=>'MICROPUNTA NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300008','nomsuministro'=>'COLORES F/CASTELL','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300009','nomsuministro'=>'CLIPS 28 MM','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300010','nomsuministro'=>'CLIPS 33 MM','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300011','nomsuministro'=>'CLIPS 50 MM','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300012','nomsuministro'=>'CLIPS 78 MM','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300014','nomsuministro'=>'FASTENER METALICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300015','nomsuministro'=>'PALANCAS SUELTAS METALICAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300016','nomsuministro'=>'CORRECTOR LIQUIDO MERLETTO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300017','nomsuministro'=>'CORRECTOR EN CINTA MADISON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300018','nomsuministro'=>'CHINCHES','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300019','nomsuministro'=>'MASQUIN ARO PEQUEÑO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300020','nomsuministro'=>'MASQUIN ARO GRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300021','nomsuministro'=>'DIUREX ARO PEQUEÑO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300022','nomsuministro'=>'SCOCH ARO GRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300023','nomsuministro'=>'CINTA DE EMBALAJE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300024','nomsuministro'=>'ENGRAMPADORA GRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300025','nomsuministro'=>'PERFORADORA PUNCH','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300026','nomsuministro'=>'PERFORADORA INDUSTRIAL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300027','nomsuministro'=>'CALCULADORA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300031','nomsuministro'=>'GOMA LIQUIDA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300032','nomsuministro'=>'GRAPAS 23/10','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300036','nomsuministro'=>'GRAPAS 26/6','idmedida'=>4]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300037','nomsuministro'=>'SACA GRAPAS MADISON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300038','nomsuministro'=>'ENGRAPADORA MEDIANA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300039','nomsuministro'=>'LAPIZ BICOLOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300040','nomsuministro'=>'LAPIZ NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300041','nomsuministro'=>'LAPIZ ROJO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300042','nomsuministro'=>'NYLON TRANSPARENTE Mts.','idmedida'=>5]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300043','nomsuministro'=>'NYLON TRANSPARENTE VINIFAN','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300044','nomsuministro'=>'Nylon VINIFAN ADHESIVO T/O PIEZAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300045','nomsuministro'=>'MARCADORES GRUESO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300046','nomsuministro'=>'MARCADORES DE AGUA DIF/COLOR.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300047','nomsuministro'=>'MARCADORES PARA CD','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300048','nomsuministro'=>'PISA PAPEL DE 25 MM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300049','nomsuministro'=>'PISA PAPEL DE 32 MM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300050','nomsuministro'=>'PORTA-ESCOCH PEQUEÑ ARTESCO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300051','nomsuministro'=>'SEÑALADORES-POSTIT','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300052','nomsuministro'=>'POSTIT DE COLORES (7x7)','idmedida'=>3]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300053','nomsuministro'=>'PESTAÑAS SEPARADORAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300055','nomsuministro'=>'REGLAS DE 30 Cm  METALICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300056','nomsuministro'=>'REGLA DE 1 METRO METALICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300057','nomsuministro'=>'RESALTADORES MONAMI COLORES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300059','nomsuministro'=>'ESTILETE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300060','nomsuministro'=>'TIJERA DE OFICINA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300061','nomsuministro'=>'TAJADOR METALICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300062','nomsuministro'=>'GOMA MIGA DE PAN','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300063','nomsuministro'=>'ALMOHADILLA MADISON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300064','nomsuministro'=>'ESPONJERO MADISON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300067','nomsuministro'=>'TINTA AZUL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300068','nomsuministro'=>'TINTA NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300069','nomsuministro'=>'TINTA ROJO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300070','nomsuministro'=>'TINTA VERDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300071','nomsuministro'=>'TAJADORES DE MESA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300072','nomsuministro'=>'UHU de 40grs.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300073','nomsuministro'=>'PORTA LAPIZ MULTIPLE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300074','nomsuministro'=>'PORTA ESCRITORIO DE MELAMINA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300075','nomsuministro'=>'PORTA BOLIGRAFO DE ESCRITORIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300076','nomsuministro'=>'BANDEJA PORTA PAPEL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300077','nomsuministro'=>'PORTA PAPEL 2 DIVICIONES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300078','nomsuministro'=>'PILA CALCURADORA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300079','nomsuministro'=>'CORDEL ROLLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300081','nomsuministro'=>'BANDERA NACIONAL DE 3 METROS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300082','nomsuministro'=>'MEDALLAS DE CONDECORACION','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300083','nomsuministro'=>'INSIGNIA DE CONDECORACION','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300084','nomsuministro'=>'FLASH MEMORI DE 8 GB.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300085','nomsuministro'=>'FECHERO AUTOMATICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300086','nomsuministro'=>'FECHERO MANUAL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300087','nomsuministro'=>'SELLO - PIE DE FIRMA 49-11','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300088','nomsuministro'=>'SELLO - PIE DE FIRMA 49-12','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300089','nomsuministro'=>'SELLO FACSIMIL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300090','nomsuministro'=>'SELLO CON FECHERO AUTOMATICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300091','nomsuministro'=>'CAMBIO GOMA DE PIE DE FIRMA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300092','nomsuministro'=>'GOMA DE SELLO 49-12','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300093','nomsuministro'=>'GOMA DE SELLO GESTION 2018','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300094','nomsuministro'=>'SELLO SECO (PLAQUETA Y PRENSA)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300095','nomsuministro'=>'BOLIGRAFOS SERIGRAFIADOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300096','nomsuministro'=>'BOLIGRAFOS DE COLORES (CAJA DE 10 UNID)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300097','nomsuministro'=>'FUNDAS DE PLASTICO T/OFICIO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300098','nomsuministro'=>'PAPELERO DE TRES DIVICIONES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300099','nomsuministro'=>'PISA PAPEL DE 50 MM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300100','nomsuministro'=>'SELLO GRANDE DE MADERA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300101','nomsuministro'=>'LLAVEROS INSTITUCIONALES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300102','nomsuministro'=>'PORTA CLIPS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300103','nomsuministro'=>'GOMA PARA SELLO SECRETARIA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300104','nomsuministro'=>'SELLO AUT. RECIBIDO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300105','nomsuministro'=>'SELLO AUT. LEGALIZADO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300106','nomsuministro'=>'GOMA PARA SELLO INSTITUCIONAL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300107','nomsuministro'=>'TABLEROS DE CAMPO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300108','nomsuministro'=>'PORTA CREDENCIALES CON CORDON 10,5X7 CM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300109','nomsuministro'=>'PINES CUMPLIMIENTO DE PLAZO 25 AÑOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300110','nomsuministro'=>'PINES JUBILACON SERVICIO VITALICIO 35 AÑOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300111','nomsuministro'=>'MICROPUNTAS 0,7 ROJO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300112','nomsuministro'=>'FOLIADOR DE 6 DIGITOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>3,'codsuministro'=>'300113','nomsuministro'=>'SELLO AUT. SECRETARIA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400001','nomsuministro'=>'DVD','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400002','nomsuministro'=>'CDs','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400003','nomsuministro'=>'PORTA CDs','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400004','nomsuministro'=>'CINTA DE IMPRESORA LQ-570','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400005','nomsuministro'=>'CINTA DE IMPRESORA LQ-590','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400006','nomsuministro'=>'CINTA IMPRESORA FX 300-100 8755','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400007','nomsuministro'=>'CINTA IMPRESORA FX 2190-2090','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400008','nomsuministro'=>'CINTA IMPRESORA LQ 2080-2070-2170-2181','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400009','nomsuministro'=>'CINTA EPSON LQ-8763','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400010','nomsuministro'=>'CINTA IMPRESORA MX','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400011','nomsuministro'=>'CINTA IMPRESORA FX 850/870/880 LX 300','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400012','nomsuministro'=>'CINTA PARA MAQUINA DE ESCRIBIR PELIKAN','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400013','nomsuministro'=>'CINTA P/MAQUIN ELECTRICA RlBBON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400014','nomsuministro'=>'CATRIDGE CANON 210 NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400015','nomsuministro'=>'CATRIDGE CANON 211 COLOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400016','nomsuministro'=>'CATRIDRIGE HP-122 NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400017','nomsuministro'=>'CATRIDRIGE HP-122 COLOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400018','nomsuministro'=>'CATRIDRIGE HP-22 COLOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400019','nomsuministro'=>'CATRIDRIGE HP-21 NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400020','nomsuministro'=>'TINTA PARA CANON NEGRO 1 LITRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400021','nomsuministro'=>'TINTA PARA CANON MAGENTA1LITRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400022','nomsuministro'=>'TINTA PARA CANON AZUL 1L','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400023','nomsuministro'=>'TINTA PARA CANON AMARILLOL 1L','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400024','nomsuministro'=>'TINTA S/CONTINUO KATASS HP UNIVERSAL COLOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400025','nomsuministro'=>'TINTA EPSON 664 NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400026','nomsuministro'=>'TINTA EPSON 664 AMARILLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400027','nomsuministro'=>'TINTA EPSON 664 AZUL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400028','nomsuministro'=>'TINTA EPSON 664 MAGENTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400029','nomsuministro'=>'DISKETTES TDK 3 1/2','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400030','nomsuministro'=>'PORTA CD´S plastico','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400031','nomsuministro'=>'TONNER DIALTA 520-620','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400032','nomsuministro'=>'TONNER HP-85A','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400033','nomsuministro'=>'TONNER HP-80A','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400034','nomsuministro'=>'TONNER HP-05A','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400035','nomsuministro'=>'TONNER KM-BH-3320','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400036','nomsuministro'=>'POLVO PARA TONNER HP','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400037','nomsuministro'=>'UNIDAD DRUM 3320','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400039','nomsuministro'=>'CABLE UTP','idmedida'=>5]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400040','nomsuministro'=>'CONECTORES RJ 45','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400041','nomsuministro'=>'ALICATE DE RED','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400042','nomsuministro'=>'HUB DE 8 PUERTOS TP/LINK','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400043','nomsuministro'=>'CORTAPICO DE 6 ENTRADAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400044','nomsuministro'=>'IMPRESORA EPSON L220','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400045','nomsuministro'=>'TONNER BIZHUB 423 P/FOTOCOPIADORA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400046','nomsuministro'=>'CORTAPICO 4 ENTRADAS C/U C/INTERRUPTOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400047','nomsuministro'=>'TONNER COMPATIBLE 80 A PRINT PLUS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400048','nomsuministro'=>'TONNER COMPATIBLE 85 A PRINT PLUS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400049','nomsuministro'=>'TONNER COMPATIBLE 05 A PRINT PLUS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400050','nomsuministro'=>'FUENTE GENERICA DE 12V 1A','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400051','nomsuministro'=>'CABLE ADAPTADOR AV1 24A5 MACHO VGA HEMBRA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400052','nomsuministro'=>'SWITCH DE 16 PUERTOS TP-LINK','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400061','nomsuministro'=>'CABLE HDMI','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400062','nomsuministro'=>'TINTA EPSON 544 NEGRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>4,'codsuministro'=>'400063','nomsuministro'=>'TARJETA DE RED PCI','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500001','nomsuministro'=>'ARRANCADORES DE 20 W. PHILIPS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500002','nomsuministro'=>'TUBOS FLUORESCENTES DE 40 WTS.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500003','nomsuministro'=>'TUBOS FLUORESCENTES DE 20 WTS.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500004','nomsuministro'=>'FOCOS PHILIPS 60W.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500005','nomsuministro'=>'FOCO AHORR. PL CALIDO DE 26 W.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500007','nomsuministro'=>'FOCOS DICROICOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500008','nomsuministro'=>'FOCO CIRCULAR DE 22 W.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500009','nomsuministro'=>'ZOCALOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500010','nomsuministro'=>'REFLECTORES LED DE 50W.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500011','nomsuministro'=>'PANTALLAS 2x40 MARCA CHILE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500012','nomsuministro'=>'INTERRUPTOR DE PARED','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500013','nomsuministro'=>'INTERRUPTOR DE PARED  DE DOS ENTRADAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500015','nomsuministro'=>'CLAVIJA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500016','nomsuministro'=>'SOQUET DE PORCELANA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500017','nomsuministro'=>'CABLE ALARGADOR DE 10 CM.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500018','nomsuministro'=>'ENCHUFES DOBLES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500019','nomsuministro'=>'PANTALLAS DE ILUMINACION','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500020','nomsuministro'=>'ADAPTADOR DE TRES ENTRADAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500021','nomsuministro'=>'CARGADOR PARA CELULAR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500022','nomsuministro'=>'CABLE ALARGADOR DE 5 M.','idmedida'=>6]);
        DB::table('alm__suministros')->insert(['idgrupo'=>5,'codsuministro'=>'500023','nomsuministro'=>'PILAS DURACELL DZ']);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600001','nomsuministro'=>'CHICOTILLO DE 40 cm.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600002','nomsuministro'=>'CHICOTILLO DE 60 cm.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600003','nomsuministro'=>'CABLE ALAMBRE Nº 12','idmedida'=>5]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600004','nomsuministro'=>'ALAMBRE Rollo','idmedida'=>6]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600005','nomsuministro'=>'BARRAS DE CABLE DUCTO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600006','nomsuministro'=>'LIJA Nº 100','idmedida'=>2]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600007','nomsuministro'=>'CINTA TEFLON','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600010','nomsuministro'=>'CHAPA PARA PUERTA CON PERILLA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600011','nomsuministro'=>'GRIFO PARA PILA NORMAL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600012','nomsuministro'=>'CHAPA PARA PUERTA NORMAL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600013','nomsuministro'=>'PILETA PARA LAVAMANOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600014','nomsuministro'=>'JALADOR DE PUERTA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600015','nomsuministro'=>'BATERIA DE BAÑO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600016','nomsuministro'=>'PICOTA PICO ANCHO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600017','nomsuministro'=>'MACHETE GRANDE M/ DE MADERA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600018','nomsuministro'=>'DESMALEZADORA BRASILERO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600019','nomsuministro'=>'TALADRO CON JUEGO DE BROCAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600020','nomsuministro'=>'PERNOS GRANDES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600021','nomsuministro'=>'PERNOS PEQUEÑOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600022','nomsuministro'=>'ESTANTE MECANO DE 5 BANDEJAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600023','nomsuministro'=>'DISPOSITIVO CELULAR SAMSUNG J1 ACE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600024','nomsuministro'=>'CHAPA FF ITALIANA 6504','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600025','nomsuministro'=>'HITILO PARA PODADORA (ROLLO)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600026','nomsuministro'=>'CHAPA ORIGINAL PAPAIZ','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600027','nomsuministro'=>'DISPOSITIVO CELULAR EWTTO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600028','nomsuministro'=>'UNION DE 1/2 PULGADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600029','nomsuministro'=>'CODOS DE 1/2 PULGADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600030','nomsuministro'=>'TE DE 1/2 PULGADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600031','nomsuministro'=>'COPLAS DE 1/2 PULGADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600032','nomsuministro'=>'CAÑERIAS DE 1/2 PULGADA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600033','nomsuministro'=>'TORNILLO DE 5 CM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600034','nomsuministro'=>'TORNILLO DE 3 CM.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600035','nomsuministro'=>'CINTA AISLANTE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600036','nomsuministro'=>'GRIFO A PRESION FV','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600037','nomsuministro'=>'RAMPLUS Nº 6','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600038','nomsuministro'=>'SILICONA UNIVERSAL SIKA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600039','nomsuministro'=>'PILAS ALCALINAS AAA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600040','nomsuministro'=>'GUARDAPOLVO DE TELA KAQUI','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600041','nomsuministro'=>'DISPOSITIVO CELULAR SAMSUNG J2 CORE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600042','nomsuministro'=>'CABLE Nº 10','idmedida'=>6]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600043','nomsuministro'=>'MANGUERA PARA AGUA','idmedida'=>5]);
        DB::table('alm__suministros')->insert(['idgrupo'=>6,'codsuministro'=>'600044','nomsuministro'=>'RASTRILLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700001','nomsuministro'=>'AMBIENTADOR LORITO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700002','nomsuministro'=>'AMBIENTADOR EN PASTlLLA P/INODORO OLA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700003','nomsuministro'=>'AROMATIC OLA - ARCHEL DE 900ml (vencido)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700004','nomsuministro'=>'SPRAY AMBIENTADOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700005','nomsuministro'=>'BASURERO DE PLASTIC CANASTILLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700006','nomsuministro'=>'CERA DE PISO FLOTANTE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700007','nomsuministro'=>'CERA DE PISO LATA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700008','nomsuministro'=>'CERA DE 26Lb LATA DE ALCOHOL','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700009','nomsuministro'=>'CERA TIGRE SACHET','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700010','nomsuministro'=>'CERA AL AGUA DE 1 LITRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700011','nomsuministro'=>'DETERGENTE ACE 2kg','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700012','nomsuministro'=>'VIRUTILLA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700013','nomsuministro'=>'ESCOBA DE PAJA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700014','nomsuministro'=>'ESCOBA PLASTICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700015','nomsuministro'=>'FRANELA NARANJA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700016','nomsuministro'=>'TOHALLAS PERSONALES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700017','nomsuministro'=>'GUANTES DE GOMA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700018','nomsuministro'=>'GUANTES DE LATEX','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700020','nomsuministro'=>'LAVANDINA LORITO 5LTS.','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700021','nomsuministro'=>'JABONCILLO LIQUIDO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700022','nomsuministro'=>'JABON UNO (vencido)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700023','nomsuministro'=>'SANITIZADOR DE MANOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700024','nomsuministro'=>'GLISERINA LIQUIDA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700025','nomsuministro'=>'LIMPIA MUEBLES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700026','nomsuministro'=>'LIMPIA VIDRIO OLA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700027','nomsuministro'=>'LAVA VAJILLAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700028','nomsuministro'=>'PAPEL HIGIENICO  ROLLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700029','nomsuministro'=>'SODA CAUSTICA 1 KILO BOLSA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700030','nomsuministro'=>'SOPAPA DE BAÑO MEDIANA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700031','nomsuministro'=>'SOPAPA DE BAÑO GRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700032','nomsuministro'=>'TRAPEADORES PLOMOS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700033','nomsuministro'=>'TRAPEADORES WAIPE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700034','nomsuministro'=>'BOLSAS NEGRAS (70x75)GRANDE','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700035','nomsuministro'=>'BOLSAS P/BASURA (65x80) MEDIANA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700036','nomsuministro'=>'BOLSAS DE BASURA (35x65)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700037','nomsuministro'=>'BARBIJOS DESCARTABLES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700038','nomsuministro'=>'CRESO PERFUMADO CHEMICAL(vencido)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700039','nomsuministro'=>'ARAGAN DE GOMA 30CM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700040','nomsuministro'=>'ARAGAN DE GOMA GRANDE DE 60cm','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700041','nomsuministro'=>'BALDE PARA TRAPEADOR','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700042','nomsuministro'=>'RECOGEDOR DE BASURA COLORES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700045','nomsuministro'=>'PAPEL HIGENICO SACA GRASA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700046','nomsuministro'=>'ECOFRESCH DE  5 LITROS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700047','nomsuministro'=>'GANCHOS PARA ROPA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700048','nomsuministro'=>'NEPTALINA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700049','nomsuministro'=>'CEPILLO P/BAÑO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700050','nomsuministro'=>'PAPEL HIGIENICO MEGA ROLLO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700051','nomsuministro'=>'DESINFECTANTE OLA DE  5 LITROS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700052','nomsuministro'=>'RECOGEDOR DE BASURA DE LATA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700053','nomsuministro'=>'TACHO 100 LTS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>7,'codsuministro'=>'700054','nomsuministro'=>'PISO DE ENTRADA GRANDE 90X60','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800001','nomsuministro'=>'CUBRE PISO DE 1,20x80 CM','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800002','nomsuministro'=>'SACO TERMICO XL - L','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800003','nomsuministro'=>'CHAQUETA TELA KAQUI','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800004','nomsuministro'=>'CHALECOS TELA KAQUI CON FORRO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800005','nomsuministro'=>'GUARDAPOLVO CON LOGO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800006','nomsuministro'=>'PANTALON TELA KAQUI','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800007','nomsuministro'=>'GUANTES DE CUERO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800008','nomsuministro'=>'GUANTES DE GOMA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800009','nomsuministro'=>'GORROS CON OREJERAS','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800010','nomsuministro'=>'SOMBRERO DE ALA ANCHA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800011','nomsuministro'=>'BOTAS DE GOMA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800012','nomsuministro'=>'BOTIN PUNTA METALICA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>8,'codsuministro'=>'800013','nomsuministro'=>'CEPILLO P/BAÑO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900001','nomsuministro'=>'ESTUCHES AZUL ASCINALSS 2012-2015','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900002','nomsuministro'=>'CEPILLOS DENTALES','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900003','nomsuministro'=>'PASTA DENTAL (vencido)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900004','nomsuministro'=>'PAPEL HIGENICO','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900005','nomsuministro'=>'SHAMPO BALLERINA (vencido)','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900006','nomsuministro'=>'TOHALLAS MEDIANA','idmedida'=>1]);
        DB::table('alm__suministros')->insert(['idgrupo'=>9,'codsuministro'=>'900007','nomsuministro'=>'JABONCILLO LUX (vencido)','idmedida'=>1]);
        
        
    }
    
}
