<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Par_MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10101','nommunicipio'=>'Sucre',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10102','nommunicipio'=>'Yotala',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10103','nommunicipio'=>'Poroma',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10201','nommunicipio'=>'Villa Azurduy',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10202','nommunicipio'=>'Tarvita',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10301','nommunicipio'=>'Villa Zudañez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10302','nommunicipio'=>'Presto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10303','nommunicipio'=>'Villa Mojocoya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10304','nommunicipio'=>'Icla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10401','nommunicipio'=>'Padilla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10402','nommunicipio'=>'Tomina',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10403','nommunicipio'=>'Sopachuy',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10404','nommunicipio'=>'Villa Alcalá',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10405','nommunicipio'=>'El Villar',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10501','nommunicipio'=>'Monteagudo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10502','nommunicipio'=>'San Pablo de Huacareta',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10601','nommunicipio'=>'Tarabuco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10602','nommunicipio'=>'Yamparáez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10701','nommunicipio'=>'Camargo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10702','nommunicipio'=>'San Lucas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10703','nommunicipio'=>'Incahuasi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10704','nommunicipio'=>'Villa Charcas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10801','nommunicipio'=>'Villa Serrano',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10901','nommunicipio'=>'Camataqui',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10902','nommunicipio'=>'Culpina',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'10903','nommunicipio'=>'Las Carreras',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'11001','nommunicipio'=>'Villa Vaca Guzmán',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'11002','nommunicipio'=>'Huacaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'1','codmunicipio'=>'11003','nommunicipio'=>'Macharetí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20101','nommunicipio'=>'La Paz',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20102','nommunicipio'=>'Palca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20103','nommunicipio'=>'Mecapaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20104','nommunicipio'=>'Achocalla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20105','nommunicipio'=>'El Alto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20201','nommunicipio'=>'Achacachi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20202','nommunicipio'=>'Ancoraimes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20203','nommunicipio'=>'Chua Cocani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20204','nommunicipio'=>'Huarina',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20205','nommunicipio'=>'Santiago de Huata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20206','nommunicipio'=>'Huatajata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20301','nommunicipio'=>'Coro Coro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20302','nommunicipio'=>'Caquiaviri',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20303','nommunicipio'=>'Calacoto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20304','nommunicipio'=>'Comanche',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20305','nommunicipio'=>'Charaña',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20306','nommunicipio'=>'Waldo Ballivián',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20307','nommunicipio'=>'Nazacara de Pacajes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20308','nommunicipio'=>'Santiago de Callapa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20401','nommunicipio'=>'Puerto Acosta',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20402','nommunicipio'=>'Mocomoco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20403','nommunicipio'=>'Puerto Carabuco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20404','nommunicipio'=>'Humanata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20405','nommunicipio'=>'Escoma',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20501','nommunicipio'=>'Chuma',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20502','nommunicipio'=>'Ayata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20503','nommunicipio'=>'Aucapata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20601','nommunicipio'=>'Sorata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20602','nommunicipio'=>'Guanay',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20603','nommunicipio'=>'Tacacoma',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20604','nommunicipio'=>'Quiabaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20605','nommunicipio'=>'Combaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20606','nommunicipio'=>'Tipuani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20607','nommunicipio'=>'Mapiri',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20608','nommunicipio'=>'Teoponte',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20701','nommunicipio'=>'Apolo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20702','nommunicipio'=>'Pelechuco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20801','nommunicipio'=>'Viacha',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20802','nommunicipio'=>'Guaqui',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20803','nommunicipio'=>'Tiahuanacu',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20804','nommunicipio'=>'Desaguadero',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20805','nommunicipio'=>'San Andrés de Machaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20806','nommunicipio'=>'Jesús de Machaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20807','nommunicipio'=>'Taraco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20901','nommunicipio'=>'Luribay',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20902','nommunicipio'=>'Sapahaqui',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20903','nommunicipio'=>'Yaco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20904','nommunicipio'=>'Malla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'20905','nommunicipio'=>'Cairoma',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21001','nommunicipio'=>'Inquisivi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21002','nommunicipio'=>'Quime',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21003','nommunicipio'=>'Cajuata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21004','nommunicipio'=>'Colquiri',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21005','nommunicipio'=>'Ichoca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21006','nommunicipio'=>'Licoma Pampa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21101','nommunicipio'=>'Chulumani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21102','nommunicipio'=>'Irupana',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21103','nommunicipio'=>'Yanacachi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21104','nommunicipio'=>'Palos Blancos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21105','nommunicipio'=>'La Asunta',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21201','nommunicipio'=>'Pucarani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21202','nommunicipio'=>'Laja',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21203','nommunicipio'=>'Batallas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21204','nommunicipio'=>'Puerto Pérez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21301','nommunicipio'=>'Sica Sica',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21302','nommunicipio'=>'Umala',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21303','nommunicipio'=>'Ayo Ayo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21304','nommunicipio'=>'Calamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21305','nommunicipio'=>'Patacamaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21306','nommunicipio'=>'Colquencha',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21307','nommunicipio'=>'Collana',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21401','nommunicipio'=>'Coroico',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21402','nommunicipio'=>'Coripata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21501','nommunicipio'=>'Ixiamas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21502','nommunicipio'=>'San Buenaventura',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21601','nommunicipio'=>'Gral. Juan José Perez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21602','nommunicipio'=>'Curva',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21701','nommunicipio'=>'Copacabana',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21702','nommunicipio'=>'San Pedro de Tiquina',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21703','nommunicipio'=>'Tito Yupanqui',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21801','nommunicipio'=>'San Pedro de Curahuara',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21802','nommunicipio'=>'Papel Pampa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21803','nommunicipio'=>'Chacarilla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21901','nommunicipio'=>'Santiago de Machaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'21902','nommunicipio'=>'Catacora',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'22001','nommunicipio'=>'Caranavi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'2','codmunicipio'=>'22002','nommunicipio'=>'Alto Beni',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30101','nommunicipio'=>'Cochabamba',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30201','nommunicipio'=>'Aiquile',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30202','nommunicipio'=>'Pasorapa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30203','nommunicipio'=>'Omereque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30301','nommunicipio'=>'Independencia',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30302','nommunicipio'=>'Morochata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30303','nommunicipio'=>'Cocapata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30401','nommunicipio'=>'Tarata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30402','nommunicipio'=>'Anzaldo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30403','nommunicipio'=>'Arbieto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30404','nommunicipio'=>'Sacabamba',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30501','nommunicipio'=>'Arani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30502','nommunicipio'=>'Vacas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30601','nommunicipio'=>'Arque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30602','nommunicipio'=>'Tacopaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30701','nommunicipio'=>'Capinota',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30702','nommunicipio'=>'Santivañez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30703','nommunicipio'=>'Sicaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30801','nommunicipio'=>'Cliza',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30802','nommunicipio'=>'Toco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30803','nommunicipio'=>'Tolata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30901','nommunicipio'=>'Quillacollo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30902','nommunicipio'=>'Sipe Sipe',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30903','nommunicipio'=>'Tiquipaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30904','nommunicipio'=>'Vinto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'30905','nommunicipio'=>'Colcapirhua',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31001','nommunicipio'=>'Sacaba',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31002','nommunicipio'=>'Colomi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31003','nommunicipio'=>'Villa Tunari',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31101','nommunicipio'=>'Tapacarí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31201','nommunicipio'=>'Totora',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31202','nommunicipio'=>'Pojo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31203','nommunicipio'=>'Pocona',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31204','nommunicipio'=>'Chimoré',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31205','nommunicipio'=>'Puerto Villarroel',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31206','nommunicipio'=>'Entre Ríos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31301','nommunicipio'=>'Mizque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31302','nommunicipio'=>'Vila Vila',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31303','nommunicipio'=>'Alalay',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31401','nommunicipio'=>'Punata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31402','nommunicipio'=>'Villa Rivero',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31403','nommunicipio'=>'San Benito',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31404','nommunicipio'=>'Tacachi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31405','nommunicipio'=>'Cuchumuela',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31501','nommunicipio'=>'Bolívar',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31601','nommunicipio'=>'Tiraque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'3','codmunicipio'=>'31602','nommunicipio'=>'Shinahota',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40101','nommunicipio'=>'Oruro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40102','nommunicipio'=>'Caracollo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40103','nommunicipio'=>'El Choro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40104','nommunicipio'=>'Soracachi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40201','nommunicipio'=>'Challapata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40202','nommunicipio'=>'Santuario de Quillacas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40301','nommunicipio'=>'Corque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40302','nommunicipio'=>'Choquecota',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40401','nommunicipio'=>'Curahuara de Carangas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40402','nommunicipio'=>'Turco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40501','nommunicipio'=>'Huachacalla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40502','nommunicipio'=>'Escara',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40503','nommunicipio'=>'Cruz de Machacamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40504','nommunicipio'=>'Yunguyo del Litoral',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40505','nommunicipio'=>'Esmeralda',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40601','nommunicipio'=>'Villa Poopó',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40602','nommunicipio'=>'Pazña',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40603','nommunicipio'=>'Antequera',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40701','nommunicipio'=>'Villa Huanuni',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40702','nommunicipio'=>'Machacamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40801','nommunicipio'=>'Salinas de Garci Mendoza',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40802','nommunicipio'=>'Pampa Aullagas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40901','nommunicipio'=>'Sabaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40902','nommunicipio'=>'Coipasa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'40903','nommunicipio'=>'Chipaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41001','nommunicipio'=>'Toledo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41101','nommunicipio'=>'Eucaliptus',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41201','nommunicipio'=>'Andamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41202','nommunicipio'=>'Belén de Andamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41301','nommunicipio'=>'Totora',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41401','nommunicipio'=>'Santiago de Huari',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41501','nommunicipio'=>'La Rivera',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41502','nommunicipio'=>'Todos Santos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41503','nommunicipio'=>'Carangas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'4','codmunicipio'=>'41601','nommunicipio'=>'Santiago de Huayllamarca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50101','nommunicipio'=>'Potosí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50102','nommunicipio'=>'Tinguipaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50103','nommunicipio'=>'Villa de Yocalla',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50104','nommunicipio'=>'Belén de Urmiri',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50201','nommunicipio'=>'Uncía',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50202','nommunicipio'=>'Chayanta',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50203','nommunicipio'=>'Llallagua',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50204','nommunicipio'=>'Chuquihuta Ayllu Jucumani',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50301','nommunicipio'=>'Betanzos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50302','nommunicipio'=>'Chaquí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50303','nommunicipio'=>'Tacobamba',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50401','nommunicipio'=>'Colquechaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50402','nommunicipio'=>'Ravelo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50403','nommunicipio'=>'Pocoata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50404','nommunicipio'=>'Ocurí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50501','nommunicipio'=>'San Pedro de Buena Vista',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50502','nommunicipio'=>'Toro Toro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50601','nommunicipio'=>'Cotagaita',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50602','nommunicipio'=>'Vitichi',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50701','nommunicipio'=>'Sacaca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50702','nommunicipio'=>'Caripuyo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50801','nommunicipio'=>'Tupiza',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50802','nommunicipio'=>'Atocha',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50901','nommunicipio'=>'Colcha K',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'50902','nommunicipio'=>'San Pedro de Quemes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51001','nommunicipio'=>'San Pablo de Lipez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51002','nommunicipio'=>'Mojinete',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51003','nommunicipio'=>'San Antonio de Esmoruco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51101','nommunicipio'=>'Puna',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51102','nommunicipio'=>'Caiza D',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51103','nommunicipio'=>'Ckochas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51201','nommunicipio'=>'Uyuni',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51202','nommunicipio'=>'Tomave',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51203','nommunicipio'=>'Porco',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51301','nommunicipio'=>'Arampampa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51302','nommunicipio'=>'Acasio',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51401','nommunicipio'=>'Llica',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51402','nommunicipio'=>'Tahua',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51501','nommunicipio'=>'Villazón',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'5','codmunicipio'=>'51601','nommunicipio'=>'San Agustín',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60101','nommunicipio'=>'Tarija',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60201','nommunicipio'=>'Padcaya',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60202','nommunicipio'=>'Bermejo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60301','nommunicipio'=>'Yacuiba',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60302','nommunicipio'=>'Caraparí',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60303','nommunicipio'=>'Villamontes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60401','nommunicipio'=>'Uriondo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60402','nommunicipio'=>'Yunchará',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60501','nommunicipio'=>'San Lorenzo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60502','nommunicipio'=>'El Puente',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'6','codmunicipio'=>'60601','nommunicipio'=>'Entre Ríos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70101','nommunicipio'=>'Santa Cruz',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70102','nommunicipio'=>'Cotoca',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70103','nommunicipio'=>'Porongo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70104','nommunicipio'=>'La Guardia',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70105','nommunicipio'=>'El Torno',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70201','nommunicipio'=>'Warnes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70202','nommunicipio'=>'Okinawa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70301','nommunicipio'=>'San Ignacio',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70302','nommunicipio'=>'San Miguel',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70303','nommunicipio'=>'San Rafael',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70401','nommunicipio'=>'Buena Vista',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70402','nommunicipio'=>'San Carlos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70403','nommunicipio'=>'Yapacaní',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70404','nommunicipio'=>'San Juan',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70501','nommunicipio'=>'San José',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70502','nommunicipio'=>'Pailón',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70503','nommunicipio'=>'Roboré',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70601','nommunicipio'=>'Portachuelo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70602','nommunicipio'=>'Santa Rosa del Sara',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70603','nommunicipio'=>'Colpa Bélgica',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70701','nommunicipio'=>'Lagunillas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70702','nommunicipio'=>'Charagua',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70703','nommunicipio'=>'Cabezas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70704','nommunicipio'=>'Cuevo',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70705','nommunicipio'=>'Gutiérrez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70706','nommunicipio'=>'Camiri',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70707','nommunicipio'=>'Boyuibe',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70801','nommunicipio'=>'Vallegrande',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70802','nommunicipio'=>'El Trigal',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70803','nommunicipio'=>'Moro Moro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70804','nommunicipio'=>'Postrervalle',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70805','nommunicipio'=>'Pucará',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70901','nommunicipio'=>'Samaipata',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70902','nommunicipio'=>'Pampa Grande',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70903','nommunicipio'=>'Mairana',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'70904','nommunicipio'=>'Quirusillas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71001','nommunicipio'=>'Montero',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71002','nommunicipio'=>'Gral. Saavedra',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71003','nommunicipio'=>'Mineros',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71004','nommunicipio'=>'Puerto Fernández Alonso',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71005','nommunicipio'=>'San Pedro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71101','nommunicipio'=>'Concepción',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71102','nommunicipio'=>'San Javier',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71103','nommunicipio'=>'San Ramón',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71104','nommunicipio'=>'San Julián',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71105','nommunicipio'=>'San Antonio de Lomerío',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71106','nommunicipio'=>'Cuatro Cañadas',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71201','nommunicipio'=>'San Matías',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71301','nommunicipio'=>'Comarapa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71302','nommunicipio'=>'Saipina',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71401','nommunicipio'=>'Puerto Suárez',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71402','nommunicipio'=>'Puerto Quijarro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71403','nommunicipio'=>'Carmen Rivero Torres',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71501','nommunicipio'=>'Ascención de Guarayos',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71502','nommunicipio'=>'Urubichá',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'7','codmunicipio'=>'71503','nommunicipio'=>'El Puente',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80101','nommunicipio'=>'Trinidad',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80102','nommunicipio'=>'San Javier',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80201','nommunicipio'=>'Riberalta',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80202','nommunicipio'=>'Guayaramerín',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80301','nommunicipio'=>'Reyes',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80302','nommunicipio'=>'San Borja',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80303','nommunicipio'=>'Santa Rosa',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80304','nommunicipio'=>'Rurrenabaque',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80401','nommunicipio'=>'Santa Ana',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80402','nommunicipio'=>'Exaltación',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80501','nommunicipio'=>'San Ignacio',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80601','nommunicipio'=>'Loreto',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80602','nommunicipio'=>'San Andrés',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80701','nommunicipio'=>'San Joaquín',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80702','nommunicipio'=>'San Ramón',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80703','nommunicipio'=>'Puerto Siles',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80801','nommunicipio'=>'Magdalena',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80802','nommunicipio'=>'Baures',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'8','codmunicipio'=>'80803','nommunicipio'=>'Huacaraje',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90101','nommunicipio'=>'Cobija',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90102','nommunicipio'=>'Porvenir',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90103','nommunicipio'=>'Bolpebra',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90104','nommunicipio'=>'Bella Flor',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90201','nommunicipio'=>'Puerto Rico',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90202','nommunicipio'=>'San Pedro',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90203','nommunicipio'=>'Filadelfia',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90301','nommunicipio'=>'Puerto Gonzalo Moreno',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90302','nommunicipio'=>'Blanca Flor',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90303','nommunicipio'=>'El Sena',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90401','nommunicipio'=>'Santa Rosa del Abuná',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90402','nommunicipio'=>'Humaita',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90501','nommunicipio'=>'Nueva Esperanza',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90502','nommunicipio'=>'Villa Nueva',]);
        DB::table('par_municipios')->insert(['iddepartamento'=>'9','codmunicipio'=>'90503','nommunicipio'=>'Santos Mercado',]);
    }
}
