<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Par_DestinosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {       
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000000','nomdestino'=>'No Identificado','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000010','nomdestino'=>'CASA MILITAR S.E.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000100','nomdestino'=>'MINISTERIO DEFENSA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000500','nomdestino'=>'TRIB.SUP.JUST.MIL.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000510','nomdestino'=>'TRIB.PERM.JUST.MIL.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000700','nomdestino'=>'REGION MIL. #1 LP','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000750','nomdestino'=>'REGION MIL. #2 OR','idmunicipio'=>164]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000800','nomdestino'=>'REGION MIL. #3 TJ','idmunicipio'=>239]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'000850','nomdestino'=>'REGION MIL. #4 SU','idmunicipio'=>1]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'001150','nomdestino'=>'COSSMIL LP','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'001300','nomdestino'=>'HOSPITAL MILITAR CENTRAL','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'001750','nomdestino'=>'COMANDO EN JEFE DE LAS FF.AA.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'002100','nomdestino'=>'ESC.MIL.INGENIERIA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'002250','nomdestino'=>'COMANDO GRAL.EJTO.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003050','nomdestino'=>'PROM.PROF.EJTO.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003100','nomdestino'=>'CENT.GRAL.MANTENIM.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003200','nomdestino'=>'INST.GEOGRAF.MIL.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003205','nomdestino'=>'ESC.MIL.TOPOGRAFIA EJTO.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003300','nomdestino'=>'RI-1 COLORADOS','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003350','nomdestino'=>'RCB-4 "INGAVI"','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003400','nomdestino'=>'BPM.B-I "SAAVEDRA"','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003450','nomdestino'=>'BAT.Y ESC.COM.1 "VIDAURRE"','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003500','nomdestino'=>'RCB-2 "TARAPACA"','idmunicipio'=>41]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003550','nomdestino'=>'RCB-1 "CALAMA"','idmunicipio'=>98]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003600','nomdestino'=>'RAA-6 "BILBAO RIOJA"','idmunicipio'=>67]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003650','nomdestino'=>'COMP.AVIACION.EJTO.1 "LOPEZ"','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003700','nomdestino'=>'CMDO.1RA.DIV.BLINDADA','idmunicipio'=>325]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003710','nomdestino'=>'PRIMERA BRIGADA MECANIZADA','idmunicipio'=>67]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003750','nomdestino'=>'RIB-8 "AYACUCHO"','idmunicipio'=>35]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003800','nomdestino'=>'RIB-23 "MAX TOLEDO"','idmunicipio'=>67]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003850','nomdestino'=>'RCB-5 "LANZA"','idmunicipio'=>68]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003900','nomdestino'=>'RA-2 "BOLIVAR"','idmunicipio'=>164]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'003950','nomdestino'=>'BAT.ING.II "ROMAN"','idmunicipio'=>115]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004000','nomdestino'=>'CMDO.2DA.DIVI.','idmunicipio'=>164]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004050','nomdestino'=>'RADIO BAT.TOPATER','idmunicipio'=>164]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004100','nomdestino'=>'RI-21 "ILLIMANI"','idmunicipio'=>203]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004150','nomdestino'=>'RI-22 "MEJILLONES"','idmunicipio'=>174]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004200','nomdestino'=>'REG.FF.EE. 24 MENDEZ ARCOS','idmunicipio'=>168]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004250','nomdestino'=>'REG.Y ESC.AND.25 "TOCOPILLA"','idmunicipio'=>172]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004300','nomdestino'=>'RC-8 "BRAUN"','idmunicipio'=>141]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004350','nomdestino'=>'RA-1 "CAMACHO"','idmunicipio'=>164]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004400','nomdestino'=>'BAT.ING.VII "SAJAMA"','idmunicipio'=>170]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004450','nomdestino'=>'CMDO.3RA.DIV.','idmunicipio'=>244]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004500','nomdestino'=>'RI-5 "CAMPERO"','idmunicipio'=>244]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004550','nomdestino'=>'RI-20 "PADILLA"','idmunicipio'=>239]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004600','nomdestino'=>'RC-3 "AROMA"','idmunicipio'=>242]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004650','nomdestino'=>'RA-3 "PISAGUA"','idmunicipio'=>244]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004700','nomdestino'=>'BAT.ING.-I CHOROLQUE','idmunicipio'=>239]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004750','nomdestino'=>'CMDO.4TA.DIV.','idmunicipio'=>275]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004800','nomdestino'=>'RI-6 "CAMPOS"','idmunicipio'=>276]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004850','nomdestino'=>'RI-11 "BOQUERON"','idmunicipio'=>271]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004900','nomdestino'=>'RC-1 "AVAROA"','idmunicipio'=>275]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'004950','nomdestino'=>'RA-4 "BULLAIN"','idmunicipio'=>273]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005000','nomdestino'=>'CMDO.5TA.DIV.','idmunicipio'=>266]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005050','nomdestino'=>'RI-13 "ISMAEL MONTES"','idmunicipio'=>264]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005100','nomdestino'=>'RI-14 "FLORIDA"','idmunicipio'=>297]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005150','nomdestino'=>'RI-15 "JUNIN"','idmunicipio'=>266]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005200','nomdestino'=>'RC-6 "CASTRILLO"','idmunicipio'=>300]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005250','nomdestino'=>'RA-5 "VERGARA"','idmunicipio'=>266]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005300','nomdestino'=>'CMDO.6TA.DIV.','idmunicipio'=>239]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005350','nomdestino'=>'RI-29 "CAP.LINO ECHEVERRIA"','idmunicipio'=>306]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005420','nomdestino'=>'RI-35 "BRUNO RACUA"','idmunicipio'=>329]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005450','nomdestino'=>'REG.Y ESC.SELVA FF.EE. 16 JORDAN','idmunicipio'=>308]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005500','nomdestino'=>'RI-17 "INDEPENDENCIA"','idmunicipio'=>309]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005550','nomdestino'=>'RC-2 "BALLIVIAN"','idmunicipio'=>319]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005600','nomdestino'=>'CMDO.7MA.DIV.','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005750','nomdestino'=>'BAT.DE TRANSPORTES III','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005800','nomdestino'=>'BAT.PM-III "ESTEBAN ARCE"','idmunicipio'=>138]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005850','nomdestino'=>'RI-2 "SUCRE"','idmunicipio'=>1]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'005900','nomdestino'=>'REG.Y ESC.PARACAID.18 "VICTORIA"','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006000','nomdestino'=>'RI-26 "GRAL.BARRIENTOS"','idmunicipio'=>144]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006050','nomdestino'=>'RI-31 "CNL.EPIFANIO RIOS"','idmunicipio'=>145]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006100','nomdestino'=>'RA-7 "TUMUSLA"','idmunicipio'=>138]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006300','nomdestino'=>'BAT.ING.-V OVANDO','idmunicipio'=>1]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006350','nomdestino'=>'ARSENAL CENTRAL']);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006352','nomdestino'=>'FUERZA DE TAREA CONJUNTA']);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006353','nomdestino'=>'GRUPO CABALL.AER."GRAL.A.SANTIAGO"','idmunicipio'=>150]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006356','nomdestino'=>'CMDO.9NA.DIVISION','idmunicipio'=>145]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006358','nomdestino'=>'RI-32 "IDELFONSO MURGUIA"','idmunicipio'=>150]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006360','nomdestino'=>'RI-33 "LADISLAO CABRERA"','idmunicipio'=>152]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006400','nomdestino'=>'CMDO.8VA.DIV.','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006500','nomdestino'=>'BAT.DE TRANSPORTES II','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006550','nomdestino'=>'BAT.PM-II "AMEZAGA"','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006600','nomdestino'=>'RI-7 "MARZANA"','idmunicipio'=>272]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006750','nomdestino'=>'RI-10 "WARNES"','idmunicipio'=>257]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006800','nomdestino'=>'REG.FF.EE. 12 MANCHEGO','idmunicipio'=>286]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006850','nomdestino'=>'BAT.ING.-III PANDO','idmunicipio'=>266]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006900','nomdestino'=>'BAT.PROD.Y ECOLOGICO III','idmunicipio'=>286]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006910','nomdestino'=>'RA. 8 "SANTA CRUZ" STA.ROSA POQUIO','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006920','nomdestino'=>'RC. 10 "CNL.JOSE MANUEL MERCADO"','idmunicipio'=>260]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'006950','nomdestino'=>'BAT.PROD.Y ECOLOGICO II','idmunicipio'=>310]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007000','nomdestino'=>'RI-30 "MURILLO"','idmunicipio'=>65]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007050','nomdestino'=>'BAT.ING.-VI RIOSINHO','idmunicipio'=>325]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007060','nomdestino'=>'BAT.POL.MIL.IV "SLDO RODOLFO SILES"','idmunicipio'=>325]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007100','nomdestino'=>'CMDO.10MA.DIV.','idmunicipio'=>220]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007150','nomdestino'=>'RI-3 "PEREZ"','idmunicipio'=>199]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007200','nomdestino'=>'RI-4 "LOA"','idmunicipio'=>230]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007250','nomdestino'=>'RI-27 "ANTOFAGASTA"','idmunicipio'=>222]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007300','nomdestino'=>'RC-7 "CHICHAS"','idmunicipio'=>220]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007350','nomdestino'=>'E.C.E.M. MCAL.S.CRUZ','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007400','nomdestino'=>'ESC.DE APLICACION DE ARMAS','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007550','nomdestino'=>'ESC.MIL.INTELIGENCIA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007600','nomdestino'=>'COLEG.MILITAR EJTO.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007650','nomdestino'=>'EMSE.MAX PAREDES','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007750','nomdestino'=>'ESC.CONDORES BOL.','idmunicipio'=>242]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007800','nomdestino'=>'LICEO MIL. ANDRADE','idmunicipio'=>1]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'007850','nomdestino'=>'ESC.MIL.MUSICA','idmunicipio'=>67]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009020','nomdestino'=>'CENTRO AGROP.#1 "CARANAVI"']);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009030','nomdestino'=>'COMANDO GENERAL DE LA FUERZA AEREA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009040','nomdestino'=>'ESC.GUERRA AEREA GRAL.BARRIENTOS','idmunicipio'=>1]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009060','nomdestino'=>'SERVICIO NACIONAL DE AEROFOT.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009120','nomdestino'=>'I-BRIGADA AEREA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009200','nomdestino'=>'GRUPO AEREO DE CAZA 31','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009220','nomdestino'=>'GRUPO AEREO DE TRANSPORTE 71','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009240','nomdestino'=>'AGEN.TAM-TAB LOCALES','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009280','nomdestino'=>'GRUPO DE ART.DEF.ANTIAEREA 91','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009320','nomdestino'=>'SERV.DE ABASTECIMIENTO AEREO 11','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009380','nomdestino'=>'III-BRIGADA AEREA','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009400','nomdestino'=>'GRUPO.AEREO DE ENTRENAMIENTO 21','idmunicipio'=>150]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009460','nomdestino'=>'GRUPO DE ARTILL.Y DEF.ANTIAEREA 93','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009540','nomdestino'=>'COLEGIO MILITAR DE AVIACION','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009580','nomdestino'=>'II-BRIGADA AEREA','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009600','nomdestino'=>'GRUPO DE ART.Y DEF.ANTIAEREA 92','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009640','nomdestino'=>'GRUPO AEREO DE CAZA 34','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009660','nomdestino'=>'GRUPO AEREO BUSQ.Y SALVAMENTO 51','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009690','nomdestino'=>'SERVICIO MANTTO. AEREO CBBA.','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009700','nomdestino'=>'POLITECNICO MILITAR DE AERONAUTICA','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009740','nomdestino'=>'IV-BRIGADA AEREA','idmunicipio'=>239]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009780','nomdestino'=>'GRUPO DE ART.Y DEF. ANTIAEREA 94','idmunicipio'=>244]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009860','nomdestino'=>'GRUPO AEREO DE EXPLOR.Y RECON. 83','idmunicipio'=>300]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009900','nomdestino'=>'GRUPO AEREO TACTICO 63','idmunicipio'=>244]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'009940','nomdestino'=>'GRUPO AEREO TACTICO 61','idmunicipio'=>266]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'010000','nomdestino'=>'GRUPO AEREO DE TRANSPORTE 72','idmunicipio'=>306]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'010060','nomdestino'=>'GRUPO AEREO TACTICO 62','idmunicipio'=>308]);
        DB::table('par__destinos')->insert(['idfuerza'=>4,'coddestino'=>'010120','nomdestino'=>'GRUPO AEREO TACTICO 64','idmunicipio'=>325]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020000','nomdestino'=>'CMDO.GRAL.ARMADA BOLIVIANA','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020220','nomdestino'=>'HIDROGRAFIA NAVAL']);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020240','nomdestino'=>'I-DIST. NAVAL BENI','idmunicipio'=>308]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020300','nomdestino'=>'BASE NAVAL "BALLIVIAN"','idmunicipio'=>313]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020320','nomdestino'=>'II-DIST.NAVAL MAMORE','idmunicipio'=>319]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020380','nomdestino'=>'B.N.PTO.VILLARROEL','idmunicipio'=>151]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020382','nomdestino'=>'AREA NAVAL # 1 "COCHABAMBA"','idmunicipio'=>117]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020383','nomdestino'=>'AREA NAVAL # 2 "SANTA CRUZ"','idmunicipio'=>250]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020390','nomdestino'=>'AREA NAVAL # 3 "BERMEJO"','idmunicipio'=>241]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020420','nomdestino'=>'III-DIST.NAV.MADERA','idmunicipio'=>309]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020520','nomdestino'=>'IV-DIST.NAV.TITICACA','idmunicipio'=>108]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020600','nomdestino'=>'V-DIST.NAV.DEL PLATA','idmunicipio'=>301]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020660','nomdestino'=>'VI-DIST.NAV.DEL ACRE','idmunicipio'=>325]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020780','nomdestino'=>'ESC.GUERRA NAVAL','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020800','nomdestino'=>'ESCUELA NAVAL MIL.','idmunicipio'=>30]);
        DB::table('par__destinos')->insert(['idfuerza'=>5,'coddestino'=>'020820','nomdestino'=>'ESC. SGTO.ZEBALLOS','idmunicipio'=>308]);
        DB::table('par__destinos')->insert(['idfuerza'=>3,'coddestino'=>'030000','nomdestino'=>'SERVICIO DIPLOMATICO']);

    }
}
